### PR TITLE
Added key for pausing [INSERT]

### PR DESCRIPTION
**Pull request by rama-adi**
I've taken the liberty to add a new keystone for pausing (Insert). This will pause the ongoing keystroke stream. The way it works is by repurposing the "Offset" feature of the program.

Quite buggy, but for now, it'll do.

### CODE REVIEW

**Comment by CosmicMustard2** [comment]
Any way that you might be able to update this? I tried to use the pause but it doesn't seem to work, and unfortunately I know nothing about coding

**Comment by rama-adi** [comment]
Idk, works okay w/my machine. i planned to rewrite this i think.
To pause you need the song to be playing first. it might not work for the first time so try a second time

**Comment by CosmicMustard2** [comment]
I tried a second time and even third and fourth time, I couldn't get it to work, could it be because I'm on a laptop?

**Comment by Stereo101** [comment]
Pausing implemented in source

**Pull request closed without merging**
