### PR TITLE
Fixed multiple things, read description

### PR DESCRIPTION
**Pull request by Raven13111**
**playSong.py:**
Fixed IndexError: list index out of range
Added song time
Changed the way exiting worked for a new load feature
Load songs using F5

**pyMIDI.py**
Auto loads playSong.py (Needed for new loading)

Stereo101, add me on discord please (@awfw)

### CODE REVIEW

**Review by Harry989 — APPROVED** [review]
Looks like a really good addition to me :)

**Review by Stereo101 — APPROVED** [review]
Looks good, should have merged earlier. Thanks for the pr.

**Comment by Stereo101** [comment]
> **playSong.py:** Fixed IndexError: list index out of range Added song time Changed the way exiting worked for a new load feature Load songs using F5
> 
> **pyMIDI.py** Auto loads playSong.py (Needed for new loading)
> 
> Stereo101, add me on discord please (@awfw)

added as collaborator if you ever feel like making more changes

**Comment by Raven13111** [comment]
Thanks

**Pull request merged**
